### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by rthomazel** [bsamaripa/scala-koans#9]
www.scalakoans.org seems to be down. Not sure if it matter but opening issue for awareness

**Comment by bsamaripa** [comment]
Hi @Thomazella, thank you for opening this issue. I already created an issue for this a few months back. I do not own the domain and would probably be best served making a static site based on the content of the original scalakoans.org. Closing as duplicate.

https://github.com/bsamaripa/scala-koans/issues/7
